apiVersion: v1
entries:
  kubeovn:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-03-27T15:32:17.468078+08:00"
    description: A Helm chart for Kubernetes
    digest: 5d65615355a18b313456fb122fdfd0b25cfd4651c0c246009d1feb1d3c0f8475
    name: kubeovn
    type: application
    urls:
    - https://hongzhen-ma.github.io/kube-ovn/kubeovn-0.1.0.tgz
    version: 0.1.0
generated: "2023-03-27T15:32:17.466269+08:00"
